// export { default as AppMain } from './app-main.vue'
export { default as NavBar } from './NavBar.vue'
// export { default as Settings } from './settings/index.vue'
export { default as Sidebar } from './sidebar/index.vue'
// export { default as TagsView } from './tags-view/index.vue'
